name: Build and Run DevWithX App

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Install dependencies
        run: npm install


      - name: Copy nginx.conf to service
        run: cp nginx.conf /etc/nginx/conf.d/default.conf

      - name: Copy certificate to SSL folder
        run: cp -r cert/. /etc/nginx/ssl

      - name: Build Next.js app
        run: npm run build

      - name: Stop Next.js app
        run: pm2 stop  nextjs-app & # Adjust command according to your project setup

      - name: Run Next.js app
        run: pm2 start npm --name "nextjs-app" -- run start # Adjust command according to your project setup
