name: Build and Run HuryDev App

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t hdevfapp:latest .

      - name: Run Docker container
        run: docker run -d -p 80:80 hdevfapp:latest
