name: Build and Run HuryDev App

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker containers
        run: docker-compose up --build -d
